services:
  # Сервис для веб-приложения
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - db_data:/app/db.sqlite3
    ports:
      - "8000:8000"

volumes:
  db_data: